theme: jekyll-theme-minimal
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false

default_layout:
  enabled: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

include:
  - index.html
  - css/
  - js/
  - images/
  - blog/
